[package]
name = "audiomirror"
version = "0.2.1"
edition = "2021"

[dependencies]
bincode = "1.3.3"
cpal = "0.15.2"
ctrlc = "3.4.0"
hound = "3.5.0"
serde = { version = "1.0.164", features = ["derive"] }
